name: framatic
description: "A view finder flutter application"
publish_to: "none"
version: 1.0.0-beta+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.0+1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  path_provider: ^2.1.1
  permission_handler: ^12.0.3
  image: ^4.1.3
  gal: ^2.3.0
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.0+2
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "framatic"
  image_path: "assets/icon/framatic.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/framatic.png"
  adaptive_icon_foreground_inset: 32
